version: '3.8'

services:
  # Servicio para la base de datos PostgreSQL
  postgres:
    image: postgres:18beta1-alpine3.22
    container_name: postgres_db
    environment:
      POSTGRES_USER: user_dataabse
      POSTGRES_PASSWORD: password_database
      POSTGRES_DB: database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reycel_app -d reycel"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Servicio para tu aplicación Express
  app:
    build: .
    container_name: express_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "direccion de tu base de datos"
      BOT_TOKEN: tocken del bot
      BOT_ID: id del chat de telegram
      USER_GMAIL: "test@gmail.com"
      PASSWORD_GMAIL: "password de gmail"
      SERVER_URL: "http://localhost:4000"
      FASTAPI_URL: "http://localhost:8000"
      URL: "http://localhost:5173"
      TOKEN_SECRET: "myPassword"
      HASH_SECRET: "ndsalkjudfglsjahgdljhsv"

    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true
    
# Volumen para persistencia de datos de PostgreSQL
volumes:
  postgres_data:

