name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
      
    - name: Login to Github Conatiner  Register
      uses: docker/login-action@v3.4.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOCKEN_CI }}

    - name: Build the Docker image Admin-dashboard
      run: |
        docker build . --file Admin-dashboard/Dockerfile --tag ghcr.io/bryan4638/reycel-admin-dashboard:latest
        docker push ghcr.io/bryan4638/reycel-admin-dashboard:latest
        
    - name: Build the Docker image Frontend
      run: |
        docker build . --file Frontend/Dockerfile --tag ghcr.io/bryan4638/reycel-frontend:latest
        docker push ghcr.io/bryan4638/reycel-frontend:latest
        
    - name: Build the Docker image Backend
      run: |
        docker build . --file Backend/Dockerfile --tag ghcr.io/bryan4638/reycel-backend:latest
        docker push ghcr.io/bryan4638/reycel-backend:latest
        
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - id: ssh
        uses: invi5H/ssh-action@v1.0.0
        with:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: 22
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: ssh ${{ steps.ssh.outputs.SERVER }} cd /root/Reycel
      - run: ssh ${{ steps.ssh.outputs.SERVER }} export TOKEN_CI=${{ secrets.TOCKEN_CI }}
      - run: ssh ${{ steps.ssh.outputs.SERVER }} ./deploy_reycel.sh
     
      
